language: ruby
rvm:
  - 2.3.0
services:
  - redis-server
  - postgresql
before_install:
  - npm i
  - gem install bundler -v 1.10.3
  - psql -c 'create database cable_chat_test;' -U postgres
install:
  - bundle install
cache:
  directories:
    - vendor/bundle
script:
  - CI=true bundle exec rspec -cfd --exclude-pattern "**/features/**/*_spec.rb"
