language: ruby
rvm:
  - 2.3.0
env:
  - DB=sqlite
services:
  - redis-server
before_install:
  - gem install bundler -v 1.10.3
install:
  - bundle install
cache:
  directories:
    - vendor/bundle
script:
  - CI=true bundle exec rspec -cfd --exclude-pattern "**/features/**/*_spec.rb"
